[package]
name = "hashsum"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
readme = "README.md"
repository = "https://github.com/edward-scroop/hashsum"
license = "GPL-3.0-or-later"

[dependencies]
